# Generated by Django 3.1.4 on 2020-12-28 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='caption',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(default=True, upload_to='gallery_photos'),
        ),
        migrations.AddField(
            model_name='photo',
            name='subject',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galleries.gallery'),
        ),
    ]
