# Generated by Django 3.1.4 on 2021-01-04 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_gallerytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallerytype',
            options={'verbose_name': 'gallery_type'},
        ),
    ]
