# Generated by Django 3.1.4 on 2021-01-04 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_auto_20210104_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_type',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='galleries.gallerytype'),
        ),
    ]
